### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gegb**

### CODE REVIEW

**Comment by be5invis** [comment]
Why revert this?

**Comment by gegb** [comment]
I think it is not necessary. And I will delete my account.

**Comment by be5invis** [comment]
> And I will delete my account
Account of what?

**Comment by gegb** [comment]
my GitHub and Coding account.

**Comment by be5invis** [comment]
> my GitHub and Coding account.

Why?

**Comment by gegb** [comment]
I register the account and Coding account just for blogging. Then I found the fonts and want to make a mirror in order to help others and me download it. Now I am no longer blogging, and I mentioned I think it is not necessary to make mirrors because almost everyone know how to download files here quickly. 并且预计很长一段时间内我没有什么需要 GitHub 的计划. So my account is no longer useful, I want to delete it.

**Comment by gegb** [comment]
zanxj 那个用户可能给您和大家带来了不快，请您理解，那不是我的本意

**Pull request merged**
